"""The hand-authored 5x7 pixel font used by Noxel's UI layer.

This module is the **source of truth** for the Latin glyphs. It is deliberately
plain data: a contributor adds a character by drawing it, and `fontgen.py`
turns the drawing into an atlas. Nothing here rasterises anything, so the font
is exactly as crisp as the grid it is drawn on — every stroke lands on a whole
pixel at 1x, and every integer upscale of it stays sharp (`Image`/`Texture`
sampling in the engine is nearest-neighbour for pixel art).

Grid
----

Each glyph is a list of 9 rows of 5 columns, in reading order:

```text
row 0   cap top          \
row 1                     |
row 2   x-height top      |  7 rows: cap height, and ascenders (b d f h k l)
row 3                     |  5 rows: x-height (a c e m n o r s u v w x z)
row 4                     |
row 5                     |
row 6   baseline         /
row 7   descender        \
row 8   descender        /   (g j p q y , ;)
```

The baseline is row 6, which is what makes a descender possible at all: a font
whose baseline is the last row cannot draw `g` without moving every other
glyph up. `fontgen.py` stores the baseline in the atlas metadata rather than
baking it into the bitmaps, so a line of mixed text can align two faces of
different heights on one baseline.

Drawing conventions
-------------------

`#` is ink, `.` is empty, and every row is exactly 5 characters. Rows are joined
with `/` in the `GLYPHS` table below so that one glyph is one line of Python and
a diff shows exactly which character changed.
"""

#: Columns in one glyph cell.
WIDTH = 5

#: Rows in one glyph cell, including the two descender rows.
HEIGHT = 9

#: The row the baseline sits on, counted from the top of the cell.
BASELINE = 6

#: Horizontal gap the renderer leaves after a glyph, in pixels.
TRACKING = 1

#: One line per glyph, laid out in fixed columns: column 0 is the character,
#: column 1 is a separator, and column 2 onwards is the cell with rows joined by
#: `/`. Fixed columns rather than a split, because the space character is a
#: perfectly good key and a whitespace split would eat it.
_ART = r"""
  ...../...../...../...../...../...../...../...../.....
! ..#../..#../..#../..#../..#../...../..#../...../.....
" .#.#./.#.#./...../...../...../...../...../...../.....
# .#.#./.#.#./#####/.#.#./#####/.#.#./.#.#./...../.....
$ ..#../.####/#.#../.###./..#.#/####./..#../...../.....
% ##..#/##.#./..#../.#.../#..../#.##./#.##./...../.....
& .##../#..#./#.#../.#.../#.#.#/#..#./.##.#/...../.....
' ..#../..#../...../...../...../...../...../...../.....
( ...#./..#../.#.../.#.../.#.../..#../...#./...../.....
) .#.../..#../...#./...#./...#./..#../.#.../...../.....
* ...../..#../#.#.#/.###./#.#.#/..#../...../...../.....
+ ...../..#../..#../#####/..#../..#../...../...../.....
, ...../...../...../...../...../...../..#../..#../.#...
- ...../...../...../#####/...../...../...../...../.....
. ...../...../...../...../...../...../..#../...../.....
/ ....#/....#/...#./..#../.#.../#..../#..../...../.....
0 .###./#...#/#..##/#.#.#/##..#/#...#/.###./...../.....
1 ..#../.##../..#../..#../..#../..#../.###./...../.....
2 .###./#...#/....#/...#./..#../.#.../#####/...../.....
3 #####/...#./..#../...#./....#/#...#/.###./...../.....
4 ...#./..##./.#.#./#..#./#####/...#./...#./...../.....
5 #####/#..../####./....#/....#/#...#/.###./...../.....
6 ..##./.#.../#..../####./#...#/#...#/.###./...../.....
7 #####/....#/...#./..#../.#.../.#.../.#.../...../.....
8 .###./#...#/#...#/.###./#...#/#...#/.###./...../.....
9 .###./#...#/#...#/.####/....#/...#./.##../...../.....
: ...../...../..#../...../...../..#../...../...../.....
; ...../...../..#../...../...../..#../..#../.#.../.....
< ...#./..#../.#.../#..../.#.../..#../...#./...../.....
= ...../...../#####/...../#####/...../...../...../.....
> .#.../..#../...#./....#/...#./..#../.#.../...../.....
? .###./#...#/....#/...#./..#../...../..#../...../.....
@ .###./#...#/#.###/#.#.#/#.###/#..../.###./...../.....
A ..#../.#.#./#...#/#...#/#####/#...#/#...#/...../.....
B ####./#...#/#...#/####./#...#/#...#/####./...../.....
C .###./#...#/#..../#..../#..../#...#/.###./...../.....
D ###../#..#./#...#/#...#/#...#/#..#./###../...../.....
E #####/#..../#..../####./#..../#..../#####/...../.....
F #####/#..../#..../####./#..../#..../#..../...../.....
G .###./#...#/#..../#.###/#...#/#...#/.###./...../.....
H #...#/#...#/#...#/#####/#...#/#...#/#...#/...../.....
I .###./..#../..#../..#../..#../..#../.###./...../.....
J ..###/...#./...#./...#./...#./#..#./.##../...../.....
K #...#/#..#./#.#../##.../#.#../#..#./#...#/...../.....
L #..../#..../#..../#..../#..../#..../#####/...../.....
M #...#/##.##/#.#.#/#.#.#/#...#/#...#/#...#/...../.....
N #...#/#...#/##..#/#.#.#/#..##/#...#/#...#/...../.....
O .###./#...#/#...#/#...#/#...#/#...#/.###./...../.....
P ####./#...#/#...#/####./#..../#..../#..../...../.....
Q .###./#...#/#...#/#...#/#.#.#/#..#./.##.#/...../.....
R ####./#...#/#...#/####./#.#../#..#./#...#/...../.....
S .####/#..../#..../.###./....#/....#/####./...../.....
T #####/..#../..#../..#../..#../..#../..#../...../.....
U #...#/#...#/#...#/#...#/#...#/#...#/.###./...../.....
V #...#/#...#/#...#/#...#/#...#/.#.#./..#../...../.....
W #...#/#...#/#...#/#.#.#/#.#.#/##.##/#...#/...../.....
X #...#/#...#/.#.#./..#../.#.#./#...#/#...#/...../.....
Y #...#/#...#/.#.#./..#../..#../..#../..#../...../.....
Z #####/....#/...#./..#../.#.../#..../#####/...../.....
[ .###./.#.../.#.../.#.../.#.../.#.../.###./...../.....
\ #..../#..../.#.../..#../...#./....#/....#/...../.....
] .###./...#./...#./...#./...#./...#./.###./...../.....
^ ..#../.#.#./#...#/...../...../...../...../...../.....
_ ...../...../...../...../...../...../...../#####/.....
` .#.../..#../...../...../...../...../...../...../.....
a ...../...../.###./....#/.####/#...#/.####/...../.....
b #..../#..../####./#...#/#...#/#...#/####./...../.....
c ...../...../.###./#..../#..../#..../.###./...../.....
d ....#/....#/.####/#...#/#...#/#...#/.####/...../.....
e ...../...../.###./#...#/#####/#..../.###./...../.....
f ..##./.#.../.#.../####./.#.../.#.../.#.../...../.....
g ...../...../.####/#...#/#...#/#...#/.####/....#/.###.
h #..../#..../####./#...#/#...#/#...#/#...#/...../.....
i ..#../...../.##../..#../..#../..#../.###./...../.....
j ...#./...../..##./...#./...#./...#./...#./#..#./.##..
k #..../#..../#..#./#.#../##.../#.#../#..#./...../.....
l .##../..#../..#../..#../..#../..#../.###./...../.....
m ...../...../##.##/#.#.#/#.#.#/#.#.#/#.#.#/...../.....
n ...../...../####./#...#/#...#/#...#/#...#/...../.....
o ...../...../.###./#...#/#...#/#...#/.###./...../.....
p ...../...../####./#...#/#...#/#...#/####./#..../#....
q ...../...../.####/#...#/#...#/#...#/.####/....#/....#
r ...../...../#.##./##..#/#..../#..../#..../...../.....
s ...../...../.####/#..../.###./....#/####./...../.....
t .#.../.#.../####./.#.../.#.../.#..#/..##./...../.....
u ...../...../#...#/#...#/#...#/#..##/.##.#/...../.....
v ...../...../#...#/#...#/#...#/.#.#./..#../...../.....
w ...../...../#...#/#.#.#/#.#.#/#.#.#/.#.#./...../.....
x ...../...../#...#/.#.#./..#../.#.#./#...#/...../.....
y ...../...../#...#/#...#/#...#/#...#/.####/....#/.###.
z ...../...../#####/...#./..#../.#.../#####/...../.....
{ ..##./.#.../.#.../##.../.#.../.#.../..##./...../.....
| ..#../..#../..#../..#../..#../..#../..#../...../.....
} .##../...#./...#./...##/...#./...#./.##../...../.....
~ ...../...../.#..#/#.#.#/#..#./...../...../...../.....
""".strip("\n")


def _parse() -> dict[str, list[str]]:
    """Turns the art table into `{character: [row, row, ...]}`.

    Raises `ValueError` on a malformed row, which is the one failure mode worth
    making loud: a row of the wrong width silently shifts every glyph after it.
    """
    glyphs: dict[str, list[str]] = {}
    for line in _ART.splitlines():
        if len(line) < 2:
            raise ValueError(f"art line is too short to hold a key: {line!r}")
        key, cell = line[0], line[2:]
        if not cell:
            raise ValueError(f"glyph {key!r} has no art")
        rows = cell.split("/")
        if len(rows) != HEIGHT:
            raise ValueError(f"glyph {key!r} has {len(rows)} rows, expected {HEIGHT}")
        for index, row in enumerate(rows):
            if len(row) != WIDTH:
                raise ValueError(
                    f"glyph {key!r} row {index} is {len(row)} wide, expected {WIDTH}: {row!r}"
                )
            if set(row) - {"#", "."}:
                raise ValueError(f"glyph {key!r} row {index} uses a character other than # or .")
        if key in glyphs:
            raise ValueError(f"glyph {key!r} is defined twice")
        glyphs[key] = rows
    return glyphs


#: Every glyph, keyed by the single character it draws.
GLYPHS: dict[str, list[str]] = _parse()


def ink_bounds(rows: list[str]) -> tuple[int, int] | None:
    """The inclusive `(first, last)` ink column, or `None` for a blank glyph."""
    columns = [x for x in range(WIDTH) if any(row[x] == "#" for row in rows)]
    if not columns:
        return None
    return columns[0], columns[-1]


if __name__ == "__main__":  # pragma: no cover - a development aid
    print(f"{len(GLYPHS)} glyphs, cell {WIDTH}x{HEIGHT}, baseline row {BASELINE}")
    missing = [chr(c) for c in range(32, 127) if chr(c) not in GLYPHS]
    print("missing printable ASCII:", missing or "none")
