//! Chunk streaming: keeps the world around a moving focus generated, and
//! answers spatial queries against what is loaded.
//!
//! The streamer owns a [`WorldGenerator`] and an LRU cache of chunks. Moving the
//! focus by a few centimetres must be nearly free, so [`WorldStreamer::update`]
//! remembers the chunk it last streamed from and returns immediately when the
//! focus has not crossed a chunk border.
//!
//! ```
//! use noxel_core::math::Vec3;
//! use noxel_world::{WorldConfig, WorldGenerator};
//! use noxel_world::stream::WorldStreamer;
//! # use std::sync::Arc;
//! # use noxel_asset::format::TileSet;
//! # let set = Arc::new(TileSet { name: "s".into(), texture: String::new(), tile_size: 16, tiles: Vec::new() });
//!
//! let generator = WorldGenerator::new(WorldConfig::new(1), set, Vec::new());
//! let mut streamer = WorldStreamer::new(generator);
//! let stats = streamer.update(Vec3::ZERO);
//! assert_eq!(stats.generated_this_update, 13 * 13);
//! assert!(stats.cache_misses > 0);
//! ```

use std::collections::HashMap;
use std::time::Instant;

use noxel_core::math::{Aabb, ChunkPos, Vec3};

use crate::chunk::{Chunk, PropInstance};
use crate::r#gen::{GenStats, WorldGenerator};

/// What a streaming update did.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct StreamStats {
    /// Chunks currently resident.
    pub loaded: usize,
    /// Chunks generated by the most recent [`WorldStreamer::update`].
    pub generated_this_update: usize,
    /// Chunks evicted by the most recent [`WorldStreamer::update`].
    pub evicted_this_update: usize,
    /// Times a needed chunk was already resident, over the streamer's lifetime.
    pub cache_hits: u64,
    /// Times a needed chunk had to be generated, over the streamer's lifetime.
    pub cache_misses: u64,
    /// Wall-clock time of the most recent update, in milliseconds.
    pub last_update_ms: f32,
    /// Approximate heap footprint of the cache, in bytes.
    pub memory_bytes: usize,
}

/// One cached chunk and the last update that touched it.
#[derive(Debug)]
struct Entry {
    chunk: Chunk,
    touched: u64,
}

/// Streams chunks around a moving focus with an LRU cache.
#[derive(Debug)]
pub struct WorldStreamer {
    generator: WorldGenerator,
    chunks: HashMap<ChunkPos, Entry>,
    /// The chunk the last update streamed from, if any.
    last_centre: Option<ChunkPos>,
    /// The view distance used by the last update.
    last_view: i32,
    /// Monotonic counter used to order LRU evictions.
    clock: u64,
    stats: StreamStats,
}

impl WorldStreamer {
    /// Creates a streamer with an empty cache.
    #[must_use]
    pub fn new(generator: WorldGenerator) -> Self {
        Self {
            generator,
            chunks: HashMap::new(),
            last_centre: None,
            last_view: -1,
            clock: 0,
            stats: StreamStats::default(),
        }
    }

    /// The generator behind this streamer.
    #[must_use]
    pub fn generator(&self) -> &WorldGenerator {
        &self.generator
    }

    /// Mutable access to the generator.
    ///
    /// Changing the *view* or *keep* distance takes effect on the next update.
    /// Changing the chunk size or the seed invalidates the cache: call
    /// [`WorldStreamer::clear`] afterwards.
    pub fn generator_mut(&mut self) -> &mut WorldGenerator {
        &mut self.generator
    }

    /// Generates and evicts so that everything within `view_distance_chunks` of
    /// `focus` exists and everything beyond `keep_distance_chunks` is dropped.
    ///
    /// Cheap when nothing changed: an update whose focus lands in the same chunk
    /// as the previous one does no work at all.
    pub fn update(&mut self, focus: Vec3) -> StreamStats {
        let started = Instant::now();
        let config = self.generator.config();
        let chunk_size = config.chunk_world_size();
        let centre = ChunkPos::from_world(focus, chunk_size);
        let view = config.view_distance_chunks.max(0);

        if self.last_centre == Some(centre) && self.last_view == view {
            // Nothing changed: report an idle update rather than the previous
            // update's counts.
            self.stats.generated_this_update = 0;
            self.stats.evicted_this_update = 0;
            self.stats.loaded = self.chunks.len();
            self.stats.last_update_ms = started.elapsed().as_secs_f32() * 1000.0;
            self.stats.memory_bytes = self.memory_bytes();
            return self.stats;
        }

        let mut generated = 0usize;
        for pos in centre.in_radius(view) {
            if self.chunks.contains_key(&pos) {
                self.stats.cache_hits += 1;
                if let Some(entry) = self.chunks.get_mut(&pos) {
                    self.clock += 1;
                    entry.touched = self.clock;
                }
            } else {
                self.stats.cache_misses += 1;
                let chunk = self.generator.generate_chunk(pos);
                self.clock += 1;
                self.chunks.insert(
                    pos,
                    Entry {
                        chunk,
                        touched: self.clock,
                    },
                );
                generated += 1;
            }
        }

        // Evict everything beyond the keep distance.
        let keep = config.keep_distance_chunks.max(view);
        let mut evicted = 0usize;
        let far: Vec<ChunkPos> = self
            .chunks
            .keys()
            .copied()
            .filter(|pos| pos.chebyshev_distance(centre) > keep)
            .collect();
        for pos in far {
            self.chunks.remove(&pos);
            evicted += 1;
        }

        // Then enforce the hard cap, furthest and least recently used first.
        let cap = config.max_cached_chunks.max(1);
        if self.chunks.len() > cap {
            let mut order: Vec<(i32, u64, ChunkPos)> = self
                .chunks
                .iter()
                .map(|(pos, entry)| (pos.chebyshev_distance(centre), entry.touched, *pos))
                .collect();
            order.sort_unstable_by(|a, b| b.0.cmp(&a.0).then(a.1.cmp(&b.1)));
            for (_, _, pos) in order {
                if self.chunks.len() <= cap {
                    break;
                }
                self.chunks.remove(&pos);
                evicted += 1;
            }
        }

        self.last_centre = Some(centre);
        self.last_view = view;
        self.stats.loaded = self.chunks.len();
        self.stats.generated_this_update = generated;
        self.stats.evicted_this_update = evicted;
        self.stats.last_update_ms = started.elapsed().as_secs_f32() * 1000.0;
        self.stats.memory_bytes = self.memory_bytes();
        self.stats
    }

    /// The chunk at `pos`, if it is loaded.
    #[must_use]
    pub fn chunk(&self, pos: ChunkPos) -> Option<&Chunk> {
        self.chunks.get(&pos).map(|entry| &entry.chunk)
    }

    /// The chunk containing a world position, if it is loaded.
    #[must_use]
    pub fn chunk_at(&self, world: Vec3) -> Option<&Chunk> {
        let pos = ChunkPos::from_world(world, self.generator.config().chunk_world_size());
        self.chunk(pos)
    }

    /// How many chunks are resident.
    #[must_use]
    pub fn loaded_chunks(&self) -> usize {
        self.chunks.len()
    }

    /// Every resident chunk.
    pub fn iter_loaded(&self) -> impl Iterator<Item = (ChunkPos, &Chunk)> {
        self.chunks.iter().map(|(pos, entry)| (*pos, &entry.chunk))
    }

    /// The chunk positions the streamer currently holds.
    #[must_use]
    pub fn loaded_positions(&self) -> Vec<ChunkPos> {
        let mut out: Vec<ChunkPos> = self.chunks.keys().copied().collect();
        out.sort_unstable();
        out
    }

    /// Tile id at a world position, if the chunk is loaded.
    #[must_use]
    pub fn tile_at(&self, world: Vec3) -> Option<u32> {
        let chunk = self.chunk_at(world)?;
        let (x, y) = chunk.world_to_tile(world)?;
        Some(chunk.tile(x, y))
    }

    /// Terrain height at a world position: exact inside a loaded chunk, and
    /// [`WorldGenerator::sample_height`] outside it.
    #[must_use]
    pub fn height_at(&self, world: Vec3) -> f32 {
        match self
            .chunk_at(world)
            .and_then(|c| c.world_to_tile(world).map(|t| (c, t)))
        {
            Some((chunk, (x, y))) => chunk.height(x, y),
            None => self.generator.sample_height(world.x, world.z),
        }
    }

    /// True when an actor may stand at a world position.
    ///
    /// Outside the loaded world this falls back to the generator's height and
    /// slope, so an entity standing on a not-yet-streamed tile still gets a
    /// sensible answer instead of a hard "no".
    #[must_use]
    pub fn is_walkable(&self, world: Vec3) -> bool {
        match self
            .chunk_at(world)
            .and_then(|c| c.world_to_tile(world).map(|t| (c, t)))
        {
            Some((chunk, (x, y))) => chunk.is_walkable(x, y, self.generator.tile_set()),
            None => {
                let height = self.generator.sample_height(world.x, world.z);
                let slope = self.generator.sample_slope(world.x, world.z);
                height >= self.generator.config().sea_level && slope <= crate::r#gen::MAX_PROP_SLOPE
            }
        }
    }

    /// True when a world position blocks line of sight.
    ///
    /// Outside the loaded world this reports `true`: the visibility system must
    /// not see through the edge of the streamed world.
    #[must_use]
    pub fn blocks_sight(&self, world: Vec3) -> bool {
        match self
            .chunk_at(world)
            .and_then(|c| c.world_to_tile(world).map(|t| (c, t)))
        {
            Some((chunk, (x, y))) => chunk.blocks_sight(x, y, self.generator.tile_set()),
            None => true,
        }
    }

    /// Collects the static colliders overlapping `region`.
    pub fn colliders_in(&self, region: Aabb, out: &mut Vec<(Aabb, u64)>) {
        for chunk in self.chunks_overlapping(&region) {
            for (bounds, id) in &chunk.colliders {
                if bounds.intersects(&region) {
                    out.push((*bounds, *id));
                }
            }
        }
    }

    /// Collects the occluder volumes overlapping `region` (buildings and props
    /// flagged as occluders) — the camera occlusion system reads this.
    pub fn occluders_in(&self, region: Aabb, out: &mut Vec<(Aabb, u64)>) {
        for chunk in self.chunks_overlapping(&region) {
            for (bounds, id) in chunk.occluder_boxes() {
                if bounds.intersects(&region) {
                    out.push((bounds, id));
                }
            }
        }
    }

    /// The props of every chunk overlapping `region`.
    pub fn props_in(&self, region: Aabb, out: &mut Vec<PropInstance>) {
        for chunk in self.chunks_overlapping(&region) {
            for prop in &chunk.props {
                if region.contains_point(prop.position) {
                    out.push(prop.clone());
                }
            }
        }
    }

    /// Approximate heap footprint of the cache, in bytes.
    #[must_use]
    pub fn memory_bytes(&self) -> usize {
        let chunks: usize = self.chunks.values().map(|e| e.chunk.memory_bytes()).sum();
        // 48 bytes is a generous estimate for a hash-map slot plus its key.
        chunks + self.chunks.len() * 48 + core::mem::size_of::<Self>()
    }

    /// The streamer's statistics.
    #[must_use]
    pub fn stats(&self) -> StreamStats {
        self.stats
    }

    /// The generator's statistics.
    #[must_use]
    pub fn gen_stats(&self) -> GenStats {
        self.generator.stats()
    }

    /// Drops every chunk, so the next update regenerates from scratch.
    pub fn clear(&mut self) {
        self.chunks.clear();
        self.last_centre = None;
        self.last_view = -1;
        self.stats.loaded = 0;
        self.stats.memory_bytes = self.memory_bytes();
    }

    /// The resident chunks whose bounds overlap `region`.
    fn chunks_overlapping(&self, region: &Aabb) -> impl Iterator<Item = &Chunk> {
        let size = self.generator.config().chunk_world_size();
        let min = ChunkPos::from_world(Vec3::new(region.min.x, 0.0, region.min.z), size);
        let max = ChunkPos::from_world(Vec3::new(region.max.x, 0.0, region.max.z), size);
        // Grow the range by one chunk: a collider clipped to a neighbouring
        // chunk can touch the region's boundary exactly, and the inclusive
        // overlap test the caller applies must still see it.
        let (min_x, max_x) = (min.x - 1, max.x + 1);
        let (min_y, max_y) = (min.y - 1, max.y + 1);
        self.chunks
            .iter()
            .filter(move |(pos, _)| {
                pos.x >= min_x && pos.x <= max_x && pos.y >= min_y && pos.y <= max_y
            })
            .map(|(_, entry)| &entry.chunk)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::r#gen::WorldConfig;
    use noxel_asset::format::{TileDef, TileFlags, TileSet};
    use std::sync::Arc;

    fn set() -> Arc<TileSet> {
        let mut tiles = Vec::new();
        for (i, name) in ["grass", "water", "road", "stone", "sand", "dirt"]
            .iter()
            .enumerate()
        {
            tiles.push(TileDef {
                id: i as u32,
                name: (*name).to_string(),
                texture: String::new(),
                uv: [0, 0, 16, 16],
                flags: TileFlags {
                    walkable: *name != "water",
                    blocks_sight: *name == "stone",
                    water: *name == "water",
                    road: *name == "road",
                    ..TileFlags::default()
                },
                height: 0.0,
                layer: 0,
            });
        }
        Arc::new(TileSet {
            name: "ground".into(),
            texture: String::new(),
            tile_size: 16,
            tiles,
        })
    }

    fn streamer(seed: u64) -> WorldStreamer {
        WorldStreamer::new(WorldGenerator::new(
            WorldConfig::new(seed),
            set(),
            Vec::new(),
        ))
    }

    #[test]
    fn update_loads_the_expected_square() {
        let mut s = streamer(1);
        let stats = s.update(Vec3::ZERO);
        let view = s.generator().config().view_distance_chunks;
        let expected = ((view * 2 + 1) * (view * 2 + 1)) as usize;
        assert_eq!(stats.generated_this_update, expected);
        assert_eq!(s.loaded_chunks(), expected);
        assert_eq!(stats.loaded, expected);
        assert_eq!(stats.cache_misses, expected as u64);
        assert_eq!(stats.cache_hits, 0);
        assert!(s.chunk(ChunkPos::ZERO).is_some());
    }

    #[test]
    fn second_update_at_the_same_place_is_free() {
        let mut s = streamer(2);
        s.update(Vec3::new(1.0, 0.0, 1.0));
        let before = s.gen_stats().chunks_generated;
        let stats = s.update(Vec3::new(5.0, 0.0, 5.0));
        assert_eq!(stats.generated_this_update, 0);
        assert_eq!(stats.evicted_this_update, 0);
        assert_eq!(s.gen_stats().chunks_generated, before);
        assert_eq!(s.loaded_chunks(), 169);
    }

    #[test]
    fn moving_one_chunk_generates_only_the_new_column_or_row() {
        let mut s = streamer(3);
        let size = s.generator().config().chunk_world_size();
        s.update(Vec3::ZERO);
        let stats = s.update(Vec3::new(size, 0.0, 0.0));
        let view = s.generator().config().view_distance_chunks;
        assert_eq!(stats.generated_this_update, (view * 2 + 1) as usize);
        assert_eq!(stats.cache_hits, (169 - (view * 2 + 1)) as u64);
        assert_eq!(stats.evicted_this_update, 0);
    }

    #[test]
    fn eviction_drops_the_far_chunks() {
        let mut s = streamer(4);
        let size = s.generator().config().chunk_world_size();
        let view = s.generator().config().view_distance_chunks;
        let keep = s.generator().config().keep_distance_chunks;
        s.update(Vec3::ZERO);
        let stats = s.update(Vec3::new(0.0, 0.0, size * 12.0));
        let centre = ChunkPos::new(0, 12);
        assert!(stats.evicted_this_update > 0, "moving must evict");
        // Everything that is left is inside the keep ring...
        for (pos, _) in s.iter_loaded() {
            assert!(
                pos.chebyshev_distance(centre) <= keep,
                "{pos:?} survived outside the keep ring"
            );
        }
        // ...and the chunks that fell out of it are gone.
        assert!(s.chunk(ChunkPos::new(0, 0)).is_none());
        assert!(s.chunk(ChunkPos::new(-view, 0)).is_none());
        // Everything inside the view square is present.
        for pos in centre.in_radius(view) {
            assert!(s.chunk(pos).is_some(), "{pos:?} should be loaded");
        }
    }

    #[test]
    fn memory_stays_bounded_over_a_long_walk() {
        let mut s = streamer(5);
        let size = s.generator().config().chunk_world_size();
        let cap = s.generator().config().max_cached_chunks;
        let mut peak = 0;
        for i in 0..40 {
            s.update(Vec3::new(i as f32 * size * 0.9, 0.0, i as f32 * size * 0.5));
            peak = peak.max(s.loaded_chunks());
            assert!(
                s.loaded_chunks() <= cap.max(169),
                "cache grew to {}",
                s.loaded_chunks()
            );
        }
        assert!(peak > 0);
        assert!(s.memory_bytes() > 0);
    }

    #[test]
    fn the_hard_cap_is_enforced() {
        let mut config = WorldConfig::new(6);
        config.max_cached_chunks = 20;
        config.view_distance_chunks = 1;
        config.keep_distance_chunks = 1;
        let mut s = WorldStreamer::new(WorldGenerator::new(config, set(), Vec::new()));
        s.update(Vec3::ZERO);
        assert!(s.loaded_chunks() <= 20, "{}", s.loaded_chunks());
    }

    #[test]
    fn tile_and_height_queries_agree_with_the_chunk() {
        let mut s = streamer(7);
        s.update(Vec3::ZERO);
        let chunk = s.chunk(ChunkPos::ZERO).unwrap().clone();
        for (x, y) in [(0u32, 0u32), (17, 3), (31, 31)] {
            let p = chunk.tile_world_center(x, y);
            assert_eq!(s.tile_at(p), Some(chunk.tile(x, y)));
            assert_eq!(s.height_at(p), chunk.height(x, y));
            assert_eq!(
                s.is_walkable(p),
                chunk.is_walkable(x, y, s.generator().tile_set())
            );
            assert_eq!(
                s.blocks_sight(p),
                chunk.blocks_sight(x, y, s.generator().tile_set())
            );
        }
    }

    #[test]
    fn queries_outside_the_loaded_world_fall_back_to_the_generator() {
        let mut s = streamer(8);
        s.update(Vec3::ZERO);
        let far = Vec3::new(100_000.0, 0.0, 100_000.0);
        assert!(s.chunk_at(far).is_none());
        assert_eq!(s.tile_at(far), None);
        assert_eq!(s.height_at(far), s.generator().sample_height(far.x, far.z));
        assert!(s.blocks_sight(far), "unknown space blocks sight");
        let walkable = s.is_walkable(far);
        assert_eq!(
            walkable,
            s.generator().sample_height(far.x, far.z) >= s.generator().config().sea_level
        );
    }

    #[test]
    fn clear_empties_the_cache() {
        let mut s = streamer(9);
        s.update(Vec3::ZERO);
        assert!(s.loaded_chunks() > 0);
        s.clear();
        assert_eq!(s.loaded_chunks(), 0);
        assert_eq!(s.stats().loaded, 0);
        let stats = s.update(Vec3::ZERO);
        assert_eq!(stats.generated_this_update, 169);
    }

    #[test]
    fn colliders_in_matches_a_brute_force_scan() {
        let mut s = streamer(10);
        // A town chunk, so the query has buildings to find.
        let spacing = s.generator().config().town_spacing_chunks;
        let size = s.generator().config().chunk_world_size();
        let centre = ChunkPos::new(spacing, spacing);
        s.update(centre.to_world_center(size, 0.0));

        let region = Aabb::new(
            Vec3::new(centre.x as f32 * size, -50.0, centre.y as f32 * size),
            Vec3::new(
                (centre.x + 1) as f32 * size,
                50.0,
                (centre.y + 1) as f32 * size,
            ),
        );
        // Brute force: scan every loaded chunk, as the streamer does, but from
        // the outside.
        let mut brute: Vec<(Aabb, u64)> = Vec::new();
        for (_, chunk) in s.iter_loaded() {
            for (bounds, id) in &chunk.colliders {
                if bounds.intersects(&region) {
                    brute.push((*bounds, *id));
                }
            }
        }
        let mut fast = Vec::new();
        s.colliders_in(region, &mut fast);
        brute.sort_by(|a, b| a.1.cmp(&b.1));
        fast.sort_by(|a, b| a.1.cmp(&b.1));
        assert_eq!(fast.len(), brute.len());
        assert_eq!(fast, brute);
        assert!(!fast.is_empty(), "a town chunk should have colliders");
    }

    #[test]
    fn occluders_in_finds_buildings_and_canopies() {
        let mut s = streamer(11);
        let spacing = s.generator().config().town_spacing_chunks;
        let size = s.generator().config().chunk_world_size();
        let centre = ChunkPos::new(spacing, spacing);
        s.update(centre.to_world_center(size, 0.0));
        let region = Aabb::new(
            Vec3::new(
                centre.x as f32 * size - size,
                -50.0,
                centre.y as f32 * size - size,
            ),
            Vec3::new(
                (centre.x + 2) as f32 * size,
                50.0,
                (centre.y + 2) as f32 * size,
            ),
        );
        let mut out = Vec::new();
        s.occluders_in(region, &mut out);
        assert!(!out.is_empty());
        for (bounds, _) in &out {
            assert!(bounds.is_finite());
            assert!(!bounds.is_empty());
            assert!(bounds.intersects(&region));
        }
    }

    #[test]
    fn colliders_in_a_region_with_no_chunks_is_empty() {
        let mut s = streamer(12);
        s.update(Vec3::ZERO);
        let region = Aabb::new(
            Vec3::new(1e6, 1e6, 1e6),
            Vec3::new(1e6 + 10.0, 1e6 + 10.0, 1e6 + 10.0),
        );
        let mut out = Vec::new();
        s.colliders_in(region, &mut out);
        assert!(out.is_empty());
    }

    #[test]
    fn props_in_matches_the_loaded_chunks() {
        let mut s = streamer(13);
        s.update(Vec3::ZERO);
        let region = Aabb::new(Vec3::new(0.0, -100.0, 0.0), Vec3::new(32.0, 100.0, 32.0));
        let mut props = Vec::new();
        s.props_in(region, &mut props);
        let expected: usize = s
            .iter_loaded()
            .map(|(_, chunk)| {
                chunk
                    .props
                    .iter()
                    .filter(|p| region.contains_point(p.position))
                    .count()
            })
            .sum();
        assert_eq!(props.len(), expected);
    }

    #[test]
    fn loaded_positions_are_sorted_and_unique() {
        let mut s = streamer(14);
        s.update(Vec3::ZERO);
        let positions = s.loaded_positions();
        let mut sorted = positions.clone();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(positions, sorted);
        assert_eq!(positions.len(), s.loaded_chunks());
    }

    #[test]
    fn stats_track_hits_and_misses() {
        let mut s = streamer(15);
        let size = s.generator().config().chunk_world_size();
        s.update(Vec3::ZERO);
        let first = s.stats();
        s.update(Vec3::new(size, 0.0, 0.0));
        let second = s.stats();
        assert!(second.cache_misses > first.cache_misses);
        assert!(second.cache_hits > first.cache_hits);
        assert!(second.last_update_ms >= 0.0);
        assert!(second.memory_bytes > 0);
    }

    #[test]
    fn zooming_out_generates_the_larger_square() {
        let mut config = WorldConfig::new(16);
        config.view_distance_chunks = 1;
        config.keep_distance_chunks = 3;
        let mut s = WorldStreamer::new(WorldGenerator::new(config, set(), Vec::new()));
        assert_eq!(s.update(Vec3::ZERO).loaded, 9);
        s.generator_mut().config_mut().view_distance_chunks = 2;
        let stats = s.update(Vec3::new(0.5, 0.0, 0.5));
        assert_eq!(stats.loaded, 25, "the streamer must notice a wider view");
        assert_eq!(stats.generated_this_update, 16);
    }
}
